# Generated by Django 4.0.6 on 2022-12-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_album_artist_song_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
